// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAW8uxPzQ8gAmDz5EeEPX9ZoSHPF5q2Zc',
    appId: '1:1071890141169:web:bc0dd6492fce70efafbe50',
    messagingSenderId: '1071890141169',
    projectId: 'study-app-f5b6b',
    authDomain: 'study-app-f5b6b.firebaseapp.com',
    storageBucket: 'study-app-f5b6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwaEDexAhoxIi12bxKrXC4qgGAVQMEcpE',
    appId: '1:1071890141169:android:fca0ce0101404eacafbe50',
    messagingSenderId: '1071890141169',
    projectId: 'study-app-f5b6b',
    storageBucket: 'study-app-f5b6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNmaTs_R3d7I77C8MFhwpG2GnSVioEyU',
    appId: '1:1071890141169:ios:3183cbb0c59a75adafbe50',
    messagingSenderId: '1071890141169',
    projectId: 'study-app-f5b6b',
    storageBucket: 'study-app-f5b6b.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNmaTs_R3d7I77C8MFhwpG2GnSVioEyU',
    appId: '1:1071890141169:ios:3183cbb0c59a75adafbe50',
    messagingSenderId: '1071890141169',
    projectId: 'study-app-f5b6b',
    storageBucket: 'study-app-f5b6b.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );
}
